twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        upload_route_name: "upload_video_locally"

when@test:
    twig:
        strict_variables: true

